INSERT INTO questions (quiz_id, question_prompt) VALUES (1, 'Guess the character! The Raccoon in Guardians of the Galaxy');
INSERT INTO questions (quiz_id, question_prompt) VALUES (1, 'Guess the character! This Bear love HUNNY');
INSERT INTO questions (quiz_id, question_prompt) VALUES (1, 'Guess the character! Sleeping Beauty');
INSERT INTO questions (quiz_id, question_prompt) VALUES (1, 'Guess the character! The Blob in Mario');
INSERT INTO questions (quiz_id, question_prompt) VALUES (1, 'Guess the character! The Pelican in The Little Mermaid');
INSERT INTO questions (quiz_id, question_prompt) VALUES (2, 'Guess the Taylor Swift Album! Dancing around all alone, Ill spend forever, Wondering if you knew, I was enchanted to meet you');
INSERT INTO questions (quiz_id, question_prompt) VALUES (2, 'Guess the Taylor Swift Album! My love was as cruel as the cities I lived in, Everyone looked worse in the light');
INSERT INTO questions (quiz_id, question_prompt) VALUES (2, 'Guess the Taylor Swift Album! You say that the past is the past, You need one chance, It was a moment of weakness, And you said yes');
INSERT INTO questions (quiz_id, question_prompt) VALUES (2, 'Guess the Taylor Swift Album! Oh, what a shame, what a rainy ending given to a perfect day');
INSERT INTO questions (quiz_id, question_prompt) VALUES (2, 'Guess the Taylor Swift Album! And clandestine meetings and stolen stares, They show their truth one single time, But they lie and they lie and they lie');
