INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 1, 'Rocket', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 1, 'Racket');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 2, 'Winnie the Pooh Bear', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 2, 'Whinny the Pooh');
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 3, 'Flora');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 3, 'Aurora', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 4, 'Star');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 4, 'Lumalee', true);
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 5, 'Scuttle', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 5, 'Seagull');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 6, 'Speak Now', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 6, 'Folklore');
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 7, 'Reputation');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 7, 'Lover', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 8, 'Red');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 8, 'Taylor Swift', true);
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 9, 'Taylor Swift', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 9, 'Fearless');
INSERT INTO answers (quiz_id, question_id, answer, is_correct) VALUES (1, 10, 'Folklore', true);
INSERT INTO answers (quiz_id, question_id, answer) VALUES (1, 10, 'Evermore');
