DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE history (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    quiz_id INTEGER REFERENCES quiz(id) ON DELETE CASCADE,
    recent_score INTEGER NOT NULL
);
