DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE History (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
    quiz_id INTEGER REFERENCES Quiz(id) ON DELETE CASCADE,
    recent_score INTEGER NOT NULL
);
